sudo: false

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run build
  - npm run test
  - COVERAGE=false FLAKEY=false PERFORMANCE=false npm run test:karma
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info
